Repository AmozPay/OtterLib, pull requests merged in 2023-02, with the labels that each got.

#52 Feature/38 window system
  OtterLib/CMakeLists.txt
  OtterLib/graphic/include/OtterGraphic.hpp
  OtterLib/graphic/src/RaylibWindow.cpp
  games/rtype/CMakeLists.txt
  games/rtype/include/Components.hpp
  games/rtype/include/System/System.hpp
  games/rtype/include/System/WindowSystem.hpp
  games/rtype/src/System/WindowSystem.cpp
  games/rtype/src/main.cpp
Labels: enhancement

#56 Feature/55 coretesting
  OtterLib/core/include/ComponentContainer.hpp
  OtterLib/core/include/Factory.hpp
  OtterLib/core/include/OtterCore.hpp
  OtterLib/core/tests/Core_test1.cpp
  OtterLib/core/tests/Core_test2.cpp
  OtterLib/core/tests/Core_test3.cpp
  OtterLib/core/tests/main.cpp
  OtterLib/core/tests/test.hpp
  OtterLib/graphic/include/Raylib.hpp
  games/rtype/include/Components.hpp
Labels: documentation, enhancement

#51 Feature/37 sprite system
  OtterLib/CMakeLists.txt
  OtterLib/graphic/src/RaylibTexture.cpp
  OtterLib/graphic/src/RaylibWindow.cpp
  games/rtype/CMakeLists.txt
  games/rtype/include/Components.hpp
  games/rtype/include/System/SpriteSystem.hpp
  games/rtype/include/System/System.hpp
  games/rtype/src/System/SpriteSystem.cpp
  games/rtype/src/assets/image.png
  games/rtype/src/main.cpp
Labels: enhancement

#58 Feature/57 add ci for tests launch
  .github/workflows/build.yml
  OtterLib/CMakeLists.txt
  README.md
  games/rtype/CMakeLists.txt
Labels: enhancement

#59 Tests: Build and run tests on push and pull requests
  .github/workflows/tests.yml
Labels: enhancement

#54 Feature/40 event system
  OtterLib/graphic/include/RaylibKeyboard.hpp
  OtterLib/graphic/src/RaylibKeyboard.cpp
  OtterLib/graphic/src/RaylibTexture.cpp
  games/rtype/include/Components.hpp
  games/rtype/include/System/EventSystem.hpp
  games/rtype/include/System/System.hpp
  games/rtype/src/System/EventSystem.cpp
  games/rtype/src/System/SpriteSystem.cpp
  games/rtype/src/main.cpp
Labels: enhancement

#53 Feature/39 move system
  games/rtype/include/System/MoveSystem.hpp
  games/rtype/include/System/System.hpp
  games/rtype/src/System/MoveSystem.cpp
  games/rtype/src/main.cpp
Labels: enhancement

#62 Add: Basic low level network read/write with stringstreams.
  OtterLib/network/include/NetChannel.hpp
  OtterLib/network/src/NetChannel.cpp
Labels: Wip

#66 Fix core test
  OtterLib/core/include/EntityManager.hpp
  OtterLib/core/include/OtterCore.hpp
  OtterLib/core/src/EntityManager.cpp
  OtterLib/core/src/OtterCore.cpp
  OtterLib/core/test/Makefile
  OtterLib/core/tests/main.cpp
  games/rtype/src/main.cpp
Labels: bug, enhancement, help wanted

#68 Feature/60 containerize application backend
  .dockerignore
  .github/workflows/release.yml
  Dockerfile
  OtterLib/CMakeLists.txt
  games/rtype/src/main.cpp
Labels: enhancement

#69 Feature/47 create documentation for engine architecture
  docs/OtterLibs/graphic/index.yml
  docs/OtterLibs/graphic/test.md
  docs/OtterLibs/network/index.yml
  docs/OtterLibs/network/test.md
  docs/PetPangolin.png
  docs/README.md
  docs/architecture/Overview.md
  docs/architecture/index.yml
  docs/integration.png
  docs/lovu_otter.png
  docs/open_docs.sh
  docs/tutorials/create_component.md
  docs/tutorials/create_system.md
  docs/tutorials/index.yml
  docs/tutorials/registrating.md
  docs/tutorials/test.md
  games/rtype/include/Components.hpp
  games/rtype/src/main.cpp
Labels: documentation

#70 Feature/30 collision system
  OtterLib/graphic/include/RaylibTexture.hpp
  OtterLib/graphic/src/RaylibTexture.cpp
  games/rtype/include/Components.hpp
  games/rtype/include/System/CollisionSystem.hpp
  games/rtype/include/System/MoveSystem.hpp
  games/rtype/include/System/System.hpp
  games/rtype/src/System/CollisionSystem.cpp
  games/rtype/src/System/MoveSystem.cpp
  games/rtype/src/main.cpp
Labels: enhancement

#75 Feature/63 add first game prototype
  OtterLib/graphic/include/RaylibKeyboard.hpp
  OtterLib/graphic/src/RaylibKeyboard.cpp
  OtterLib/graphic/src/RaylibWindow.cpp
  games/rtype/include/Components.hpp
  games/rtype/include/System/EventSystem.hpp
  games/rtype/include/Utils.hpp
  games/rtype/src/System/EventSystem.cpp
  games/rtype/src/assets/image.png
  games/rtype/src/assets/obstacle.gif
  games/rtype/src/assets/spaceship.gif
  games/rtype/src/main.cpp
Labels: enhancement

#71 Fix: component heritance manager
  OtterLib/core/include/Orchestrator.hpp
  OtterLib/core/include/registry.hpp
  OtterLib/core/src/test.cpp
  OtterLib/core/tests/Core_test1.cpp
  OtterLib/core/tests/Core_test2.cpp
  OtterLib/core/tests/Core_test3.cpp
  OtterLib/core/tests/test.hpp
  OtterLib/graphic/src/RaylibWindow.cpp
  games/rtype/include/Components.hpp
  games/rtype/include/System/System.hpp
  games/rtype/src/main.cpp
Labels: bug, enhancement

#78 Feature/65 player can shoot
  OtterLib/graphic/include/RaylibKeyboard.hpp
  OtterLib/graphic/include/RaylibTexture.hpp
  OtterLib/graphic/include/RaylibWindow.hpp
  OtterLib/graphic/src/RaylibTexture.cpp
  OtterLib/graphic/src/RaylibWindow.cpp
  games/rtype/include/Components.hpp
  games/rtype/include/System/DispawnableSystem.hpp
  games/rtype/include/System/EventSystem.hpp
  games/rtype/include/System/System.hpp
  games/rtype/include/System/WindowSystem.hpp
  games/rtype/include/Utils.hpp
  games/rtype/src/System/DispawnableSystem.cpp
  games/rtype/src/System/EventSystem.cpp
  games/rtype/src/System/MoveSystem.cpp
  games/rtype/src/System/WindowSystem.cpp
  games/rtype/src/assets/background.png
  games/rtype/src/assets/projectile.gif
  games/rtype/src/main.cpp
Labels: enhancement

#80 Add: Component builders in core and game
  OtterLib/core/include/Factory.hpp
  OtterLib/core/include/Orchestrator.hpp
  OtterLib/core/src/Factory.cpp
  games/rtype/CMakeLists.txt
  games/rtype/include/Components.hpp
  games/rtype/src/component_utils.cpp
  games/rtype/src/entities/player.json
Labels: enhancement

#81 Feature/79 event handler component
  games/rtype/include/Components.hpp
  games/rtype/include/System/EventNetworkSystem.hpp
  games/rtype/include/System/System.hpp
  games/rtype/src/System/EventNetworkSystem.cpp
  games/rtype/src/System/EventSystem.cpp
  games/rtype/src/System/WindowSystem.cpp
  games/rtype/src/main.cpp
Labels: enhancement

#83 Fix: compil error
  games/rtype/include/Components.hpp
  games/rtype/src/main.cpp
Labels: enhancement

#87 Add: Lua/5.4.4 dependency
  OtterLib/conanfile.txt
Labels: enhancement

#102 refactor: abstract Raylib keyboard managment
  OtterLib/graphic/include/OtterGraphicKeyboard.hpp
  OtterLib/graphic/include/RaylibKeyboard.hpp
  OtterLib/graphic/src/RaylibKeyboard.cpp
  games/rtype/include/Components.hpp
  games/rtype/src/System/EventSystem.cpp
  games/rtype/src/main.cpp
Labels: enhancement

#106 Feature/86 create a lua scripting prototype with c
  CONTRIBUTING.md
  OtterLib/CMakeLists.txt
  OtterLib/core/include/EntityManager.hpp
  OtterLib/core/include/Factory.hpp
  OtterLib/core/include/Orchestrator.hpp
  OtterLib/core/include/OtterCore.hpp
  OtterLib/core/include/SystemManager.hpp
  OtterLib/core/src/EntityManager.cpp
  OtterLib/core/src/Factory.cpp
  OtterLib/core/src/OtterCore.cpp
  OtterLib/core/tests/main.cpp
  OtterLib/graphic/src/RaylibTexture.cpp
  OtterLib/scripting/include/C2LuaBindings.hpp
  OtterLib/scripting/include/ScriptedComponent.hpp
  OtterLib/scripting/include/ScriptingManager.hpp
  OtterLib/scripting/include/lua_wrapper.hpp
  OtterLib/scripting/src/C2LuaBindings.cpp
  OtterLib/scripting/src/ScriptingManager.cpp
  OtterLib/scripting/src/lua_wrapper.cpp
  OtterLib/scripting/tests/ScriptingManager.test.cpp
  OtterLib/scripting/tests/lua_wrapper.test.cpp
  OtterLib/scripting/tests/test_data/functions.lua
  OtterLib/scripting/tests/test_data/hello.lua
  games/rtype/CMakeLists.txt
  games/rtype/include/Components.hpp
  games/rtype/src/component_utils.cpp
  games/rtype/src/scripts/main.lua
  tools/install_hooks.sh
Labels: enhancement, help wanted

#111 feat: add new assets for game
  games/rtype/src/assets/enemy1-34x34.png
  games/rtype/src/assets/enemy2-29x22.png
  games/rtype/src/assets/ennemyShoot1-31x4.png
  games/rtype/src/assets/ennemyShoot2-16x16.png
  games/rtype/src/assets/joueur1-32x14.png
  games/rtype/src/assets/joueur2-32x14.png
  games/rtype/src/assets/joueur3-32x14.png
  games/rtype/src/assets/joueur4-32x14.png
  games/rtype/src/assets/parallax-1920x1080.png
  games/rtype/src/assets/shoot1-16x8.png
  games/rtype/src/assets/shoot2-48x12.png
Labels: enhancement

#109 feature: 72 add static mob
  OtterLib/graphic/include/OtterGraphicKeyboard.hpp
  OtterLib/graphic/include/RaylibKeyboard.hpp
  OtterLib/graphic/include/RaylibTexture.hpp
  OtterLib/graphic/src/RaylibKeyboard.cpp
  OtterLib/graphic/src/RaylibTexture.cpp
  games/rtype/CMakeLists.txt
  games/rtype/include/Component/EventComponent.hpp
  games/rtype/include/Components.hpp
  games/rtype/include/System/CollisionSystem.hpp
  games/rtype/include/System/Collisions/CollisionSystem.hpp
  games/rtype/include/System/Collisions/EnemyCollisionSystem.hpp
  games/rtype/include/System/Collisions/EventCollisionSystem.hpp
  games/rtype/include/System/Collisions/ObstacleCollisionSystem.hpp
  games/rtype/include/System/Collisions/PlayerCollisionSystem.hpp
  games/rtype/include/System/DeathSystem.hpp
  games/rtype/include/System/EventHandlerSystem.hpp
  games/rtype/include/System/EventNetworkSystem.hpp
  games/rtype/include/System/EventSystem.hpp
  games/rtype/include/System/InputKeySystem.hpp
  games/rtype/include/System/System.hpp
  games/rtype/include/Utils.hpp
  games/rtype/src/System/CollisionSystem.cpp
  games/rtype/src/System/Collisions/CollisionSystem.cpp
  games/rtype/src/System/Collisions/EnemyCollisionSystem.cpp
  games/rtype/src/System/Collisions/EventCollisionSystem.cpp
  games/rtype/src/System/Collisions/ObstacleCollisionSystem.cpp
  games/rtype/src/System/Collisions/PlayerCollisionSystem.cpp
  games/rtype/src/System/DeathSystem.cpp
  games/rtype/src/System/EventHandlerSystem.cpp
  games/rtype/src/System/EventNetworkSystem.cpp
  games/rtype/src/System/InputKeySystem.cpp
  games/rtype/src/System/SpriteSystem.cpp
  games/rtype/src/assets/mobs.gif
  games/rtype/src/main.cpp
Labels: enhancement

#110 Feature/108 create animation system
  OtterLib/graphic/include/RaylibTexture.hpp
  OtterLib/graphic/src/RaylibTexture.cpp
  games/rtype/CMakeLists.txt
  games/rtype/include/Component/AnimationComponent.hpp
  games/rtype/include/Components.hpp
  games/rtype/include/System/AnimationSystem.hpp
  games/rtype/include/Utils/Animation.hpp
  games/rtype/src/System/AnimationSystem.cpp
  games/rtype/src/System/EventNetworkSystem.cpp
  games/rtype/src/System/SpriteSystem.cpp
  games/rtype/src/main.cpp
Labels: enhancement

#113 Feature/107 create entities from lua
  OtterLib/CMakeLists.txt
  OtterLib/core/include/OtterCore.hpp
  OtterLib/core/include/SystemManager.hpp
  OtterLib/core/src/OtterCore.cpp
  OtterLib/scripting/OtterLib.lua
  OtterLib/scripting/include/C2LuaBindings.hpp
  OtterLib/scripting/include/ScriptingManager.hpp
  OtterLib/scripting/include/lua_wrapper.hpp
  OtterLib/scripting/src/C2LuaBindings.cpp
  OtterLib/scripting/src/ScriptingManager.cpp
  OtterLib/scripting/src/lua_wrapper.cpp
  OtterLib/scripting/tests/ScriptingManager.test.cpp
  games/rtype/CMakeLists.txt
  games/rtype/src/scripts/.gitignore
  games/rtype/src/scripts/main.lua
Labels: bug, enhancement

#115 refacto: clean main
  games/rtype/CMakeLists.txt
  games/rtype/include/Game/GameClient.hpp
  games/rtype/include/Game/GameServer.hpp
  games/rtype/src/Game/GameClient.cpp
  games/rtype/src/Game/GameServer.cpp
  games/rtype/src/main.cpp
Labels: enhancement

#117 Feature/114 move components to lib + create lua bindings
  OtterLib/CMakeLists.txt
  OtterLib/core/include/ComponentUtils.hpp
  OtterLib/core/include/baseComponents.hpp
  OtterLib/scripting/OtterLib.lua
  OtterLib/scripting/include/C2LuaBindings.hpp
  OtterLib/scripting/include/ScriptingManager.hpp
  OtterLib/scripting/include/lua_wrapper.hpp
  OtterLib/scripting/src/C2LuaBindings.cpp
  OtterLib/scripting/src/ScriptingManager.cpp
  OtterLib/scripting/src/lua_wrapper.cpp
  OtterLib/scripting/tests/ScriptingManager.test.cpp
  games/rtype/src/scripts/main.lua
Labels: enhancement

#120 Feature/119 delete duplicate components between game and lib
  OtterLib/core/include/OtterCore.hpp
  OtterLib/core/src/OtterCore.cpp
  OtterLib/scripting/include/ScriptingManager.hpp
  OtterLib/scripting/src/ScriptingManager.cpp
  games/rtype/include/Components.hpp
  games/rtype/src/Game/GameClient.cpp
  games/rtype/src/Game/GameServer.cpp
  games/rtype/src/System/Collisions/CollisionSystem.cpp
  games/rtype/src/System/Collisions/EnemyCollisionSystem.cpp
  games/rtype/src/System/Collisions/EventCollisionSystem.cpp
  games/rtype/src/System/Collisions/PlayerCollisionSystem.cpp
  games/rtype/src/System/DeathSystem.cpp
  games/rtype/src/System/DispawnableSystem.cpp
  games/rtype/src/System/EventNetworkSystem.cpp
  games/rtype/src/System/InputKeySystem.cpp
  games/rtype/src/System/MoveSystem.cpp
  games/rtype/src/System/ParallaxSystem.cpp
  games/rtype/src/System/SpriteSystem.cpp
  games/rtype/src/System/WindowSystem.cpp
  games/rtype/src/scripts/main.lua
Labels: enhancement
