Repository AmozPay/OtterLib, pull requests merged in 2023-01, with the labels that each got.

#17 Feature/5 create basic engine
  OtterLib/core/include/ComponentContainer.hpp
  OtterLib/core/include/EntityManager.hpp
  OtterLib/core/include/Orchestrator.hpp
  OtterLib/core/include/OtterCore.hpp
  OtterLib/core/include/SystemManager.hpp
  OtterLib/core/include/registry.hpp
  OtterLib/core/src/EntityManager.cpp
  OtterLib/core/src/registry.cpp
  OtterLib/core/src/test.cpp
  OtterLib/core/test/Makefile
Labels: enhancement, help wanted

#21 Feature/18 abstract main
  OtterLib/core/include/Orchestrator.hpp
  OtterLib/core/include/OtterCore.hpp
  OtterLib/core/include/SystemManager.hpp
  OtterLib/core/src/OtterCore.cpp
  OtterLib/core/src/endPointDev.cpp
  OtterLib/core/src/main.cpp
  OtterLib/core/src/test.cpp
  OtterLib/core/test/Makefile
Labels: enhancement

#14 Feature/8 handle extern dependencies in cmake
  .github/workflows/build.yml
  .gitignore
  CMakeLists.txt
  CMakelists.txt
  OtterLib/CMakeLists.txt
  OtterLib/conanfile.txt
  games/CMakeLists.txt
  games/rtype/CMakeLists.txt
  games/rtype/conanfile.txt
  games/rtype/src/main.cpp
Labels: enhancement

#25 Add: phase management
  OtterLib/core/include/SystemManager.hpp
  OtterLib/core/src/OtterCore.cpp
  OtterLib/core/src/endPointDev.cpp
  OtterLib/core/src/test.cpp
Labels: enhancement

#26 Feature/22 factory
  OtterLib/core/include/Factory.hpp
  OtterLib/core/include/Orchestrator.hpp
  OtterLib/core/include/OtterCore.hpp
  OtterLib/core/src/Factory.cpp
  OtterLib/core/src/endPointDev.cpp
  games/rtype/src/main.cpp
Labels: enhancement

#42 Bugfix/41 conan x cmake build
  .github/workflows/build.yml
  OtterLib/CMakeLists.txt
  OtterLib/conanfile.txt
  OtterLib/graphic/include/OtterGraphic.hpp
  OtterLib/graphic/src/test.cpp
  games/rtype/CMakeLists.txt
  games/rtype/conanfile.txt
  games/rtype/src/main.cpp
Labels: bug

#34 Tests: Add google tests for OtterLib
  .gitignore
  OtterLib/CMakeLists.txt
  OtterLib/core/tests/main.cpp
  OtterLib/graphic/tests/main.cpp
  OtterLib/network/tests/main.cpp
Labels: enhancement

#20 Feature/16 encapsulate raylib lib for graphics
  OtterLib/graphic/include/OtterGraphic.hpp
  OtterLib/graphic/include/Raylib.hpp
  OtterLib/graphic/include/RaylibKeyboard.hpp
  OtterLib/graphic/include/RaylibMouse.hpp
  OtterLib/graphic/include/RaylibMusic.hpp
  OtterLib/graphic/include/RaylibSound.hpp
  OtterLib/graphic/include/RaylibText.hpp
  OtterLib/graphic/include/RaylibTexture.hpp
  OtterLib/graphic/include/RaylibWindow.hpp
  OtterLib/graphic/src/RaylibKeyboard.cpp
  OtterLib/graphic/src/RaylibMouse.cpp
  OtterLib/graphic/src/RaylibMusic.cpp
  OtterLib/graphic/src/RaylibSound.cpp
  OtterLib/graphic/src/RaylibText.cpp
  OtterLib/graphic/src/RaylibTexture.cpp
  OtterLib/graphic/src/RaylibWindow.cpp
  OtterLib/graphic/src/test.cpp
Labels: enhancement

#45 Feature/36 basic components
  OtterLib/graphic/include/OtterGraphic.hpp
  games/rtype/CMakeLists.txt
  games/rtype/include/Components.hpp
  games/rtype/include/Utils.hpp
  games/rtype/src/main.cpp
Labels: enhancement

#49 Feature/19 create a serialization system
  OtterLib/core/include/Factory.hpp
  OtterLib/graphic/src/test.cpp
  OtterLib/network/include/Deserializer/Deserializer.hpp
  OtterLib/network/include/Networkable/Class/Class.hpp
  OtterLib/network/include/Networkable/Networkable.hpp
  OtterLib/network/include/Networkable/Variable/Variable.hpp
  OtterLib/network/include/Serializable/Serializable.hpp
  OtterLib/network/include/Serializer/Serializer.hpp
  OtterLib/network/src/nothing.cpp
  OtterLib/network/src/test.cpp
  games/rtype/src/main.cpp
Labels: enhancement
